<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Go back' => 'Volver',
    'Administrator' => 'Administrador',
    'Answer' => 'Respuesta',
    'Are you sure you want to close the ticket?' => 'Seguro que queres cerrar este ticket',
    'Client' => 'Cliente',
    'Close' => 'Cerrar',
    'Date' => 'Fecha',
    'Date Updated' => 'Editado',
    'Delete' => 'Borrar',
    'Departament' => 'Departamento',
    'Developer' => 'Programador',
    'Do you really want to delete?' => 'Seguro que queres borrar el ticket',
    'Document name' => 'Nombre del Documento',
    'File Name' => 'Nombre del Archivo',
    'Go Back' => 'Volver',
    'ID' => 'ID',
    'Id Body' => 'Codigo de Mensaje',
    'In progress' => 'En progreso',
    'Link' => 'Link',
    'Message' => 'Mensaje',
    'Name User' => 'Nombre de Usuario',
    'New Ticket' => 'Nuevo Ticket',
    'Open' => 'Abrir',
    'Open New Ticket' => 'Abrir New Ticket',
    'Reply' => 'Responder',
    'Send Ticket' => 'Enviar Ticket',
    'Status' => 'Estatus',
    'Text' => 'Texto',
    'This email is generated automatically by the system notification service. You do not need to respond to it.' => 'Este mail fue generado automaticamente. Por favor no lo responda',
    'Ticket' => 'Ticket',
    'User ID' => 'Codigo de Usuario',
    'Username' => 'Usuario',
    'Waiting' => 'Esperando',
    'Тopic' => 'Categoria',
];
