<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administrator' => '',
    'Answer' => '',
    'Are you sure you want to close the ticket?' => '',
    'Client' => '',
    'Close' => '',
    'Date' => '',
    'Date Updated' => '',
    'Delete' => '',
    'Departament' => '',
    'Developer' => '',
    'Do you really want to delete?' => '',
    'Document name' => '',
    'File Name' => '',
    'Go Back' => '',
    'Go back' => '',
    'ID' => '',
    'Id Body' => '',
    'In progress' => '',
    'Link' => '',
    'Message' => '',
    'Name User' => '',
    'New Ticket' => '',
    'Open' => '',
    'Open New Ticket' => '',
    'Reply' => '',
    'Send Ticket' => '',
    'Status' => '',
    'Text' => '',
    'This email is generated automatically by the system notification service. You do not need to respond to it.' => '',
    'Ticket' => '',
    'User ID' => '',
    'Username' => '',
    'Waiting' => '',
    'Тopic' => '',
    'Send ticket' => '@@@@',
];
